spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/softwareengineer
    username: root
    password: 123456


#mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.softwareEngineer.entity
server:
  port: 8080
#spring事务日志管理
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug


